**R Programming apply family of functions**

In this experiment we will learn about how to use apply family of functions
to do data wrangling and avaoid use of looping constructs 

The R base manual tells you that it’s called as follows: 

```
apply(X, MARGIN, FUN, ...)
```


```X``` is an array or a matrix if the dimension of the array is ```2```

```MARGIN``` is a variable defining how the function is applied: 
 

*   When ```MARGIN=1```, it applies over rows 
*   Whereas with ```MARGIN=2```, it works over columns
*   ```MARGIN=c(1,2)```, it applies to both rows and columns;     

and
```FUN```, represents the function that you want to apply to the data. It can be any R function, including a User Defined Function (UDF).

In [1]:
# Complete the following code by using apropriate apply family function
# Construct a 5x6 matrix
X <-matrix(rnorm(30), nrow=5, ncol=6)
X



[,1]       [,2]        [,3]       [,4]      [,5]      [,6]       
[1,]  0.9682121  1.47009764 -1.4797638 0.8231903 0.7257017  0.75268143
[2,]  0.6524728 -0.09476405 -0.5607604 0.3484111 0.6273941 -1.21861419
[3,] -0.1602522 -1.58036665 -0.9467710 2.4123196 1.1411656  1.05482329
[4,] -1.8381030  0.48838673  1.0952776 0.5658090 1.5730651  0.02272337
[5,] -0.8349197 -1.20335465 -0.4842745 1.0392172 0.5604167 -0.20120869

In [2]:
# Sum the values of each column with apply()
X_colsum <- apply(X,2,sum)
X_colsum

[1] -1.2125899 -0.9200010 -2.3762922  5.1889472  4.6277432  0.4104052

In [3]:
# Sum the values of each row with apply()
X_rowsum <- apply(X,1,sum)
X_rowsum

[1]  3.2601194 -0.2458607  1.9209186  1.9071588 -1.1241236

The **lapply()** Function is used when You want to apply a given function to every element of a list and obtain a list as a result.
 
 Syntax of **lapply()** looks like the **apply()** function.

There is a slight difference in way they work, which is :



1.   **lapply()** can be used for other objects like dataframes, lists or vectors
2.   The output returned by **lapply()** is a list (which explains the “l” in the function name), which has the same number of elements as the object passed to it.

To see how this works, complete the following code block.

**lapply()** is a quite common operation performed on real data when making comparisons or aggregations from different dataframes.


In [4]:
# Using sequence 1:9 create a matrix A with size 3*3
A <- matrix(1:9, nrow=3, ncol=3)
A

#Using sequence 4:15 create a matrix B with size 4*3

#Using sequnce 8:10 create a matrix C with size 3*2

# create variable MyList as list of matrix A, B, C


# Using lapply and [ operator Extract the 2nd column from `MyList` with the selection operator `[` with `lapply()`

# Using lapply and [ operator Extract the 4th row from `MyList` with the selection operator `[` with `lapply()`


# Using lapply and [ operator Extract the 1st row from `MyList` with the selection operator `[` with `lapply()`



[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [5]:
#Using sequence 4:15 create a matrix B with size 4*3
B <- matrix(4:15, nrow=4, ncol=3)
B

[,1] [,2] [,3]
[1,] 4     8   12  
[2,] 5     9   13  
[3,] 6    10   14  
[4,] 7    11   15

In [6]:
#Using sequnce 8:10 create a matrix C with size 3*2
C <- matrix(8:10, nrow=3, ncol=2)
C

[,1] [,2]
[1,]  8    8  
[2,]  9    9  
[3,] 10   10

In [7]:
# create variable MyList as list of matrix A, B, C
MyList <- list(A, B, C)
MyList

[[1]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[2]]
     [,1] [,2] [,3]
[1,]    4    8   12
[2,]    5    9   13
[3,]    6   10   14
[4,]    7   11   15

[[3]]
     [,1] [,2]
[1,]    8    8
[2,]    9    9
[3,]   10   10

In [8]:
# Using lapply and [ operator Extract the 2nd column from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', , 2)

[[1]]
[1] 4 5 6

[[2]]
[1]  8  9 10 11

[[3]]
[1]  8  9 10

In [9]:
# Using lapply and [ operator Extract the 4th row from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', 4, )
# Error Occurs because in MyList there are 3 matrix where matrix A and C is having only 3 rows

ERROR: ignored

In [10]:
# Using lapply and [ operator Extract the 1st row from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', 1, )

[[1]]
[1] 1 4 7

[[2]]
[1]  4  8 12

[[3]]
[1] 8 8

The **sapply()** Function

The **sapply()** function works like **lapply()**, but it tries to simplify the output to the most elementary data structure that is possible. And indeed, ```sapply()``` is a **‘wrapper’** function for **lapply()**.

Let’s repeat the extraction operation of a single element as in the last example, but now take the first element of the second row (indexes 2 and 1) for each matrix.

Applying the **lapply()** function would give us a list unless you pass ```simplify=FALSE``` as a parameter to **sapply()**. Then, a list will be returned. See how it works in the code chunk below:



In [11]:
# Return a list with `lapply()`
lapply(MyList,"[", 2, 1 )

# Return a vector with `sapply()`
sapply(MyList,"[", 2, 1 )

# Return a list with `sapply()`
sapply(MyList,"[", 2, 1, simplify=F)

# Return a vector with `unlist()`
unlist(lapply(MyList,"[", 2, 1 ))

[[1]]
[1] 2

[[2]]
[1] 5

[[3]]
[1] 9

[1] 2 5 9

[[1]]
[1] 2

[[2]]
[1] 5

[[3]]
[1] 9

[1] 2 5 9

In this Text Block Write note on mapply function and give exampe code and exaplain use of mapply function.

1.  The arguments for mapply are mapply(FUN, …, MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE). Firstly list the function, followed by the vectors you are using. The rest of the arguments have default values so they don’t need to be changed. When you have a function that takes 2 arguments, the first vector goes into the first argument and the second vector goes into the second argument.


In [12]:
# Example use of mapply function
mapply(rep, 1:9, 9:1)

[[1]]
[1] 1 1 1 1 1 1 1 1 1

[[2]]
[1] 2 2 2 2 2 2 2 2

[[3]]
[1] 3 3 3 3 3 3 3

[[4]]
[1] 4 4 4 4 4 4

[[5]]
[1] 5 5 5 5 5

[[6]]
[1] 6 6 6 6

[[7]]
[1] 7 7 7

[[8]]
[1] 8 8

[[9]]
[1] 9